ARG CONTAINER_VERSION_TAG=ubi:8.10

FROM registry.access.redhat.com/ubi8/${CONTAINER_VERSION_TAG}

ENV BUILDER=/tmp/builder

RUN mkdir ${BUILDER}
WORKDIR ${BUILDER}
COPY --chmod=0755 scripts/install-dependencies.sh ${BUILDER}/install-dependencies.sh
RUN ${BUILDER}/install-dependencies.sh

COPY --chmod=0755 scripts/cleanup-dnf.sh ${BUILDER}/cleanup-dnf.sh
RUN ${BUILDER}/cleanup-dnf.sh

WORKDIR /

USER root
