ARG BASE_IMAGE=python:3.11-slim-jammy
FROM ${BASE_IMAGE}

ARG COMPLIANCE_AS_CODE_VERSION=0.1.78
ENV COMPLIANCE_AS_CODE_VERSION=${COMPLIANCE_AS_CODE_VERSION}

ENV BUILDER=/tmp/builder

RUN mkdir ${BUILDER}
WORKDIR ${BUILDER}
COPY --chmod=0755 scripts/install-dependencies.sh ${BUILDER}/install-dependencies.sh
RUN ${BUILDER}/install-dependencies.sh --version ${COMPLIANCE_AS_CODE_VERSION}

COPY --chmod=0755 scripts/cleanup-apt.sh ${BUILDER}/cleanup-apt.sh
RUN ${BUILDER}/cleanup-apt.sh

WORKDIR /

# Create non-root user for Python slim base image
RUN groupadd -g 1001 appuser && useradd -u 1001 -g appuser appuser
USER 1001