ARG BASE_IMAGE=registry.redhat.io/ubi9/python-311
FROM ${BASE_IMAGE}

#Install Dependencies to Run STIGs
ARG COMPLIANCE_AS_CODE_VERSION=0.1.78
ENV BUILDER=/tmp/builder
ENV COMPLIANCE_AS_CODE_VERSION=${COMPLIANCE_AS_CODE_VERSION}

#Install Dependencies
USER root
RUN mkdir ${BUILDER}
WORKDIR ${BUILDER}
COPY --chmod=0755 scripts/install-dependencies.sh ${BUILDER}/install-dependencies.sh 
RUN ${BUILDER}/install-dependencies.sh --version ${COMPLIANCE_AS_CODE_VERSION}

COPY --chmod=0755 scripts/cleanup-dnf.sh ${BUILDER}/cleanup-dnf.sh
RUN ${BUILDER}/cleanup-dnf.sh

USER 1001
