name: Build and Test UBI 8.9 Image
on:
  pull_request:
    types: [opened, synchronize, reopened]
    
env:
  CONTAINER_TAG: "ubi"
  CONTAINER_MAJOR_VERSION: "8"
  CONTAINER_MINOR_VERSION: "9"
jobs:

  build-test-ubi8-image:
    
    runs-on: ubuntu-latest
    steps:
     #The formatting on this first line might be different for the CONTAINER_VERSION_TAG, but hopefully the rest is standard and can be copied and pasted as needed for follow on container builds.
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --no-cache --file Dockerfile.ubi8 --build-arg CONTAINER_VERSION_TAG="${{env.CONTAINER_TAG}}:${{env.CONTAINER_MAJOR_VERSION}}.${{env.CONTAINER_MINOR_VERSION}}" --tag "localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}"
    - name: Vulnerability scan image
      id: ubi8-scan
      uses: anchore/scan-action@v3
      with:
        image: "localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}"
        only-fixed: true  
        severity-cutoff: critical
    - name: Upload Vulnerability Scan
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.ubi8-scan.outputs.sarif }}
    - name: DoD Scap Scan
      run: docker build . --no-cache --file Dockerfile.DoDscap --build-arg CONTAINER="localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}" --tag "localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}-scap"
    - uses: shrink/actions-docker-extract@v3
      id: "ubi8-extract-scap"
      with:
        image: "localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}-scap"
        path: /root/SCC/Sessions
        destination: "ubi8-scap-output"
    - name: Upload Scap Results
      uses: actions/upload-artifact@v4
      with:
        name: "UBI8 DoD SCAP Scan Results"
        path: "ubi8-scap-output"
    - name: Openscap Scan
      run: docker build . --file Dockerfile.Openscap --build-arg CONTAINER="localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}" --tag "localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}-scap"
    - uses: shrink/actions-docker-extract@v3
      id: "ubi8-extract-openscap"
      with:
        image: "localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}-scap"
        path: /tmp/openscap.html
        destination: "ubi8-openscap-output"
    - name: Upload Scap Results
      uses: actions/upload-artifact@v4
      with:
        name: "Openscap Scan Results"
        path: "ubi8-openscap-output"
    - name: Run Inspec Scan
      run: chmod a+x ./scripts/inspec-scan.sh && ./scripts/inspec-scan.sh localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}
    - name: RunInspec Scan
      run: docker build . --no-cache --file Dockerfile.inspec --build-arg CONTAINER="localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}" --tag "localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}-inspec"
    - name: Extract Inspec Results
      uses: shrink/actions-docker-extract@v3
      id: "ubi8-extract-inspec"
      with:
        image: "localbuild/${{env.CONTAINER_TAG}}-${{env.CONTAINER_MAJOR_VERSION}}-${{env.CONTAINER_MINOR_VERSION}}-inspec"
        path: /tmp/junit.xml
        destination: ubi8-inspec-output
    - name: PublishInspec Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      with:
        files: |
          ubi8-inspec-output/junit.xml
    - name: UploadInspec output
      uses: actions/upload-artifact@v4
      with:
        name: "UBI8 Inspec Scan Results"
        path: ubi8-inspec-output
